"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
"""

i = 2 # last number
s = 1 # sum
while True:
    num = 1 # number of divisors
    s += i
    k = s
    p = 2
    while k != 1:    
        prime = True
        for j in range(2,int(p**0.5)+1):
            if p % j == 0:
                prime = False
                break
        if prime:
            t = 1
            while k % p == 0:
                k /= p
                t += 1
            num *= t
        p += 1
    if num > 500:
        print(s)
        break
    i+=1
